default:
  # Environment
  num_envs: 1
  steps: 1e8
  replay_size: 1e6
  time_limit: 1000
  batch_length: 64
  batch_size: 16
  train_ratio: 512
  log_every: 1e3
  eval_every: 1e4
  eval_eps: 5
  eval_steps: 300
  prefill: 2500
  pretrain: 100
  device: 'cuda'
  ssh: True  # rick: 129.67.95.58; huey: 129.67.95.84
  record: False
  real_time_eval: False
  zero_shot: False
  save_datasets: False

  # Model
  h_dim: 512
  z_dim: 1024
  layers: [512, 512]
  act: silu
  ensemble_size: 5

  # Training
  model_lr: 1e-4
  model_eps: 1e-8
  model_grad_clip: 1000
  actor_lr: 3e-5
  critic_lr: 3e-5
  ac_eps: 1e-5
  ac_grad_clip: 100
  weight_decay: 1e-6
  beta_dyn: 0.5
  beta_repr: 0.1
  gamma: 0.997
  lam: 0.95
  entropy_coeff: 3e-4
  imag_horizon: 15
  slow_critic_update: 1
  slow_critic_fraction: 0.02
  action_repeat: 2
  init_zero: False
  unimix_ratio: 0.01
  init_deter: 'zero'

  # Exploration
  Plan2Explore: False
  explore_steps: 1e6
  explore_coeff: 500
  init_std: 1
  max_std: 1
  min_std: 0.1

raisim:
  batch_length: 64
  action_repeat: 1
  log_every: 2e2
  eval_every: 1e4
  eval_eps: 2
  eval_steps: 150
  render: True
  num_threads: 8
  real_time_eval: True
  sim_dt: 0.005
  control_dt: 0.04
  add_velocity_noise: False
  action_clip: 1
  random_init_state: True
  reward:
    linVel: 0 #4
    angVel: 0 #2
    torque: 0 #-1e-5
    jointSpeed: 0 #-1e-3
  terminal_reward: -1
  commands:
    fwdVelMax: 1
    latVelMax: 0.4
    turnVelMax: 1.2

ditto:
  ditto_wm_steps: 1000
  ditto_il_steps: 1e6
  ditto_batch_size: 512

debug:
  num_envs: 1
  prefill: 300
  pretrain: 4
  log_every: 10
  eval_every: 200
  time_limit: 1000
  eval_eps: 5
  eval_steps: 300
  device: 'cuda'
  rick: False
  ditto_wm_steps: 10